/*
BSD License

Copyright (c) 2016, Frédéric Yvon Vinet
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
* The name of its author may not be used to endorse or promote products
  derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.nemesis.antlr.v4.netbeans.v8.grammar.file;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.io.File;
import java.nio.file.Path;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToolBar;
import javax.swing.SwingConstants;
import org.nemesis.antlr.v4.netbeans.v8.grammar.file.preview.UndoRedoProvider;
import org.nemesis.antlr.v4.netbeans.v8.grammar.file.preview.AdhocMimeTypes;
import org.nemesis.antlr.v4.netbeans.v8.grammar.file.preview.ui.PreviewPanel;
import org.netbeans.core.spi.multiview.CloseOperationState;
import org.netbeans.core.spi.multiview.MultiViewElement;
import org.netbeans.core.spi.multiview.MultiViewElementCallback;
import org.openide.awt.StatusDisplayer;
import org.openide.awt.UndoRedo;
import org.openide.cookies.SaveCookie;
import org.openide.filesystems.FileUtil;

import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.Mutex;
import org.openide.util.NbBundle.Messages;
import org.openide.util.RequestProcessor;

import org.openide.windows.TopComponent;

@MultiViewElement.Registration(
        displayName = "#LBL_G4_VISUAL",
        iconBase = "org/nemesis/antlr/v4/netbeans/v8/grammar/file/antlr-g4-file-type.png",
        mimeType = "text/x-g4",
        persistenceType = TopComponent.PERSISTENCE_NEVER,
        preferredID = "G4Visual",
        position = 2000
)
@Messages({"LBL_G4_VISUAL=Tester", "LBL_LOADING=Loading..."})
public final class G4VisualElement extends JPanel implements MultiViewElement, LookupListener {

    private final G4DataObject obj;
    private final JToolBar toolbar = new JToolBar();
    private transient MultiViewElementCallback callback;
    private final JLabel loadingLabel = new JLabel(Bundle.LBL_LOADING());
    private static final Logger LOG = Logger.getLogger(
            G4VisualElement.class.getName());
    private static final RequestProcessor INIT
            = new RequestProcessor(G4VisualElement.class.getName(), 3);
    private final MutableProxyLookup lkp;
    private UndoRedo undoRedo = UndoRedo.NONE;
    private Lookup.Result<SaveCookie> saveCookieResult;

    public G4VisualElement(Lookup lkp) {
        obj = lkp.lookup(G4DataObject.class);
        this.lkp = new MutableProxyLookup(lkp);
        assert obj != null;
        initComponents();
        loadingLabel.setHorizontalAlignment(SwingConstants.CENTER);
        loadingLabel.setVerticalAlignment(SwingConstants.CENTER);
        loadingLabel.setEnabled(false);
        add(loadingLabel, BorderLayout.CENTER);
    }

    @Override
    public String getName() {
        return "G4VisualElement";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public JComponent getVisualRepresentation() {
        return this;
    }

    @Override
    public JComponent getToolbarRepresentation() {
        return toolbar;
    }

    @Override
    public Action[] getActions() {
        return callback == null ? new Action[0] : callback.createDefaultActions();
    }

    @Override
    public Lookup getLookup() {
        return lkp;
    }

    private RequestProcessor.Task initTask;

    @Messages({
        "# {0} - grammar file path",
        "NOT_A_FILE=Not a valid file: {0}",
        "# {0} - grammar file path",
        "NOT_REGULAR_FILE=Virtual files cannot be parsed by Antlr: {0}",
        "# {0} - grammar file path",
        "REGISTERING_DYNAMIC=Compiling {0} and registering syntax highlighting",
        "# {0} - grammar file path",
        "REGISTERING_COMPLETE=Language registration complete: {0}"
    })
    private void lazyInit() {
        LOG.log(Level.FINER, "Lazy init for {0}", obj.getPrimaryFile().getPath());
        if (initTask != null) {
            LOG.log(Level.WARNING, "Init for {0} called twice", obj.getPrimaryFile().getPath());
            return;
        }
        if (obj.isValid()) {
            File file = FileUtil.toFile(obj.getPrimaryFile());
            if (file != null) {
                StatusDisplayer.getDefault().setStatusText(
                        Bundle.REGISTERING_DYNAMIC(obj.getPrimaryFile().getNameExt()));
                initTask = INIT.create(() -> {
                    _lazyInit(file.toPath());
                });
                initTask.schedule(50);
            } else {
                loadingLabel.setText(Bundle.NOT_REGULAR_FILE(obj.getPrimaryFile().getPath()));
            }
        } else {
            loadingLabel.setText(Bundle.NOT_A_FILE(obj.getPrimaryFile().getPath()));
        }
    }

    private void _lazyInit(Path path) {
        assert !EventQueue.isDispatchThread();
        // XXX theoretically the file can be deleted between lazyInit() and
        // this being run on a background thread
        String mime = AdhocMimeTypes.mimeTypeForPath(path);
        LOG.log(Level.FINER, "Background lanugage registration of {0}"
                + " as pseudo-mime-type {1}", new Object[]{obj.getPrimaryFile().getPath(), mime});
        long then = System.currentTimeMillis();
        EventQueue.invokeLater(() -> {
            StatusDisplayer.getDefault()
                    .setStatusText(
                            Bundle.REGISTERING_COMPLETE(obj.getPrimaryFile().getNameExt()));
            LOG.log(Level.FINEST,
                    "Lazy load completed in {0} ms", new Object[]{
                        System.currentTimeMillis() - then});
            PreviewPanel pnl = new PreviewPanel(mime, obj.getLookup());
            UndoRedoProvider prov = pnl.getLookup().lookup(UndoRedoProvider.class);
            if (prov != null) {
                this.undoRedo = prov.get();
                super.firePropertyChange("undoRedo", UndoRedo.NONE, undoRedo);
            }
            this.lkp.setAdditional(pnl.getLookup());
            saveCookieResult = pnl.getLookup().lookupResult(SaveCookie.class);
            saveCookieResult.addLookupListener(this);
            remove(loadingLabel);
            add(pnl, BorderLayout.CENTER);
        });
    }

    @Override
    public void componentOpened() {
        lazyInit();
    }

    @Override
    public void componentClosed() {
    }

    @Override
    public void componentShowing() {
    }

    @Override
    public void componentHidden() {
    }

    @Override
    public void componentActivated() {
    }

    @Override
    public void componentDeactivated() {
    }

    @Override
    public UndoRedo getUndoRedo() {
        return undoRedo;
    }

    @Override
    public void setMultiViewCallback(MultiViewElementCallback callback) {
        this.callback = callback;
    }

    @Override
    public CloseOperationState canCloseElement() {
        return CloseOperationState.STATE_OK;
    }

    @Override
    public void resultChanged(LookupEvent le) {
        if (callback != null) {
            Mutex.EVENT.readAccess((Runnable) () -> {
                Collection<? extends SaveCookie> all = saveCookieResult.allInstances();
                if (callback != null) {
                    if (all.isEmpty()) {
                        callback.updateTitle(obj.getName());
                    } else {
                        callback.updateTitle("<b>" + obj.getName() + "-hey*");
                    }
                }
            });
        }
    }
}
