package org.nemesis.registration.typenames;

/**
 * <b>DO NOT MODIFY THIS FILE!</b> This file is generated by analyzing the POMs
 * and class files used in all subprojects of theparent project for class names
 * that are likely to be used in codegeneration. It will be regenerated at build
 * time.
 **/
public enum Libraries implements Library {

    ACTIONS("org.netbeans.api", "org-openide-actions", "RELEASE112"),
    COMMON("org.netbeans.api", "org-netbeans-api-annotations-common",
        "RELEASE112"),
    ANTLR_LANGUAGE("com.mastfrog", "antlr-language-spi", "2.0.14"),
    REFACTORING("com.mastfrog", "antlr-refactoring", "2.0.14"),
    UTILS("com.mastfrog", "antlr-utils", "2.0.14"),
    ANTLR_WRAPPER("com.mastfrog", "antlr-wrapper", "2.0.14"),
    API("org.netbeans.contrib.yenta", "api", "1.1"),
    AWT("org.netbeans.api", "org-openide-awt", "RELEASE112"),
    COMPLETION("com.mastfrog", "antlr-language-code-completion", "2.0.14"),
    ANTLR_COMMON("com.mastfrog", "antlr-common", "2.0.14"),
    CODE_COMPLETION("com.mastfrog", "antlr-code-completion", "2.0.14"),
    DIALOGS("org.netbeans.api", "org-openide-dialogs", "RELEASE112"),
    DOCUMENT("org.netbeans.api", "org-netbeans-modules-editor-document",
        "RELEASE112"),
    EDITOR("org.netbeans.api", "org-netbeans-modules-editor", "RELEASE112"),
    EDITOR_COMPLETION("org.netbeans.api",
        "org-netbeans-modules-editor-completion", "RELEASE112"),
    EDITOR_UTILS("com.mastfrog", "editor-utils", "2.0.14"),
    EXTRACTION("com.mastfrog", "extraction", "2.0.14"),
    FILESYSTEMS("org.netbeans.api", "org-openide-filesystems", "RELEASE112"),
    FILTERS("com.mastfrog", "character-filters", "2.0.14"),
    FOLD("org.netbeans.api", "org-netbeans-modules-editor-fold", "RELEASE112"),
    FOLDING("com.mastfrog", "antlr-code-folding", "2.0.14"),
    FORMATTERS("com.mastfrog", "antlr-formatters", "2.0.14"),
    FORMATTING("com.mastfrog", "antlr-language-formatting", "2.0.14"),
    UI("com.mastfrog", "antlr-language-formatting-ui", "2.0.14"),
    HELPERS("com.mastfrog", "antlr-project-helpers", "2.0.14"),
    HIGHLIGHTING("com.mastfrog", "antlr-highlighting", "2.0.14"),
    HINTS("org.netbeans.api", "org-netbeans-spi-editor-hints", "RELEASE112"),
    INDENT("org.netbeans.api", "org-netbeans-modules-editor-indent",
        "RELEASE112"),
    INDEXING("org.netbeans.api", "org-netbeans-modules-parsing-indexing",
        "RELEASE112"),
    INPUT("com.mastfrog", "antlr-input", "2.0.14"),
    IO("org.netbeans.api", "org-openide-io", "RELEASE112"),
    LEXER("org.netbeans.api", "org-netbeans-modules-lexer", "RELEASE112"),
    LIB("org.netbeans.api", "org-netbeans-modules-editor-lib", "RELEASE112"),
    LIB2("org.netbeans.api", "org-netbeans-modules-editor-lib2", "RELEASE112"),
    LOADERS("org.netbeans.api", "org-openide-loaders", "RELEASE112"),
    LOCALIZERS("com.mastfrog", "localizers", "2.0.14"),
    LOOKUP("org.netbeans.api", "org-openide-util-lookup", "RELEASE112"),
    MIMELOOKUP("org.netbeans.api", "org-netbeans-modules-editor-mimelookup",
        "RELEASE112"),
    MODELS("com.mastfrog", "extraction-data-models", "2.0.14"),
    MODULES("org.netbeans.api", "org-openide-modules", "RELEASE112"),
    MULTIVIEW("org.netbeans.api", "org-netbeans-core-multiview", "RELEASE112"),
    NAVIGATOR("org.netbeans.api", "org-netbeans-spi-navigator", "RELEASE112"),
    NAVIGATORS("com.mastfrog", "antlr-navigators", "2.0.14"),
    NODES("org.netbeans.api", "org-openide-nodes", "RELEASE112"),
    UTIL("org.netbeans.api", "org-openide-util", "RELEASE112"),
    OPTIONS_EDITOR("org.netbeans.modules", "org-netbeans-modules-options-editor",
        "RELEASE112"),
    PARSER("com.mastfrog", "tiny-ebnf-parser", "2.0.14"),
    PARSING("org.netbeans.api", "org-netbeans-modules-parsing-api", "RELEASE112"),
    PROJECTAPI("org.netbeans.api", "org-netbeans-modules-projectapi",
        "RELEASE112"),
    QUERIES("org.netbeans.api", "org-netbeans-modules-queries", "RELEASE112"),
    MODULES_REFACTORING("org.netbeans.api",
        "org-netbeans-modules-refactoring-api", "RELEASE112"),
    REFACTORING_COMMON("com.mastfrog", "antlr-refactoring-common", "2.0.14"),
    RENAME("com.mastfrog", "antlr-instant-rename", "2.0.14"),
    RESOLVER("com.mastfrog", "antlr-grammar-file-resolver", "2.0.14"),
    RUNTIME("org.antlr", "antlr-runtime", "3.5.2"),
    SETTINGS("org.netbeans.api", "org-netbeans-modules-editor-settings",
        "RELEASE112"),
    SUPPORT("com.mastfrog", "antlr-file-support", "2.0.14"),
    TEST_LANGUAGE("com.mastfrog", "simple-test-language", "2.0.14"),
    TEXT("org.netbeans.api", "org-openide-text", "RELEASE112"),
    UTIL_UI("org.netbeans.api", "org-openide-util-ui", "RELEASE112"),
    EDITOR_UTIL("org.netbeans.api", "org-netbeans-modules-editor-util",
        "RELEASE112"),
    SWING_UTILS("com.mastfrog", "swing-utils", "2.0.14"),
    WINDOWS("org.netbeans.api", "org-openide-windows", "RELEASE112"),
    WRAPPER("com.mastfrog", "mastfrog-utils-wrapper", "2.0.14")
    ;
    private final String groupId;
    private final String artifactId;
    private final String version;

    Libraries(String groupId, String artifactId, String version) {
        this.groupId = groupId;
        this.artifactId = artifactId;
        this.version = version;
    }

    @Override
    public String groupId() {
        return groupId;
    }

    @Override
    public String artifactId() {
        return artifactId;
    }

    @Override
    public String version() {
        return version;
    }

    @Override
    public String toString() {
        return groupId + ":" + artifactId + ":" + version;
    }

}
