package org.nemesis.registration.typenames;

/**
 * <b>DO NOT MODIFY THIS FILE!</b> This file is generated by analyzing the POMs
 * and class files used in all subprojects of theparent project for class names
 * that are likely to be used in codegeneration. It will be regenerated at build
 * time.
 **/
public enum Libraries implements Library {

    ACTIONS("org.netbeans.api", "org-openide-actions", "RELEASE111"),
    COMMON("com.mastfrog", "antlr-common", "2.0.5"),
    ANTLR_LANGUAGE("com.mastfrog", "antlr-language-spi", "2.0.5"),
    REFACTORING("com.mastfrog", "antlr-refactoring", "2.0.5"),
    ANTLR_WRAPPER("com.mastfrog", "antlr-wrapper", "2.0.5"),
    API("org.netbeans.contrib.yenta", "api", "1.1"),
    AWT("org.netbeans.api", "org-openide-awt", "RELEASE111"),
    COMPLETION("com.mastfrog", "antlr-language-code-completion", "2.0.5"),
    ANNOTATIONS_COMMON("org.netbeans.api", "org-netbeans-api-annotations-common",
        "RELEASE111"),
    CODE_COMPLETION("com.mastfrog", "antlr-code-completion", "2.0.5"),
    DIALOGS("org.netbeans.api", "org-openide-dialogs", "RELEASE111"),
    DOCUMENT("org.netbeans.api", "org-netbeans-modules-editor-document",
        "RELEASE111"),
    EDITOR("org.netbeans.api", "org-netbeans-modules-editor", "RELEASE111"),
    EDITOR_COMPLETION("org.netbeans.api",
        "org-netbeans-modules-editor-completion", "RELEASE111"),
    EXTRACTION("com.mastfrog", "extraction", "2.0.5"),
    FILESYSTEMS("org.netbeans.api", "org-openide-filesystems", "RELEASE111"),
    FILTERS("com.mastfrog", "character-filters", "2.0.5"),
    FOLD("org.netbeans.api", "org-netbeans-modules-editor-fold", "RELEASE111"),
    FOLDING("com.mastfrog", "antlr-code-folding", "2.0.5"),
    FORMATTERS("com.mastfrog", "antlr-formatters", "2.0.5"),
    FORMATTING("com.mastfrog", "antlr-language-formatting", "2.0.5"),
    UI("com.mastfrog", "antlr-language-formatting-ui", "2.0.5"),
    HELPERS("com.mastfrog", "antlr-project-helpers", "2.0.5"),
    HIGHLIGHTING("com.mastfrog", "antlr-highlighting", "2.0.5"),
    HINTS("org.netbeans.api", "org-netbeans-spi-editor-hints", "RELEASE111"),
    INDENT("org.netbeans.api", "org-netbeans-modules-editor-indent",
        "RELEASE111"),
    INDEXING("org.netbeans.api", "org-netbeans-modules-parsing-indexing",
        "RELEASE111"),
    INPUT("com.mastfrog", "antlr-input", "2.0.5"),
    IO("org.netbeans.api", "org-openide-io", "RELEASE111"),
    LEXER("org.netbeans.api", "org-netbeans-modules-lexer", "RELEASE111"),
    LIB("org.netbeans.api", "org-netbeans-modules-editor-lib", "RELEASE111"),
    LIB2("org.netbeans.api", "org-netbeans-modules-editor-lib2", "RELEASE111"),
    LOADERS("org.netbeans.api", "org-openide-loaders", "RELEASE111"),
    LOCALIZERS("com.mastfrog", "localizers", "2.0.5"),
    LOOKUP("org.netbeans.api", "org-openide-util-lookup", "RELEASE111"),
    MIMELOOKUP("org.netbeans.api", "org-netbeans-modules-editor-mimelookup",
        "RELEASE111"),
    MODELS("com.mastfrog", "extraction-data-models", "2.0.5"),
    NAVIGATOR("org.netbeans.api", "org-netbeans-spi-navigator", "RELEASE111"),
    NAVIGATORS("com.mastfrog", "antlr-navigators", "2.0.5"),
    NODES("org.netbeans.api", "org-openide-nodes", "RELEASE111"),
    UTIL("org.netbeans.api", "org-openide-util", "RELEASE111"),
    OPTIONS_EDITOR("org.netbeans.modules", "org-netbeans-modules-options-editor",
        "RELEASE111"),
    PARSING("org.netbeans.api", "org-netbeans-modules-parsing-api", "RELEASE111"),
    PROJECTAPI("org.netbeans.api", "org-netbeans-modules-projectapi",
        "RELEASE111"),
    QUERIES("org.netbeans.api", "org-netbeans-modules-queries", "RELEASE111"),
    MODULES_REFACTORING("org.netbeans.api",
        "org-netbeans-modules-refactoring-api", "RELEASE111"),
    REFACTORING_COMMON("com.mastfrog", "antlr-refactoring-common", "2.0.5"),
    RENAME("com.mastfrog", "antlr-instant-rename", "2.0.5"),
    RESOLVER("com.mastfrog", "antlr-grammar-file-resolver", "2.0.5"),
    RUNTIME("org.antlr", "antlr-runtime", "3.5.2"),
    SETTINGS("org.netbeans.api", "org-netbeans-modules-editor-settings",
        "RELEASE111"),
    SUPPORT("com.mastfrog", "antlr-file-support", "2.0.5"),
    TEST_LANGUAGE("com.mastfrog", "simple-test-language", "2.0.5"),
    TEXT("org.netbeans.api", "org-openide-text", "RELEASE111"),
    UTIL_UI("org.netbeans.api", "org-openide-util-ui", "RELEASE111"),
    EDITOR_UTIL("org.netbeans.api", "org-netbeans-modules-editor-util",
        "RELEASE111"),
    UTILS("com.mastfrog", "editor-utils", "2.0.5"),
    WINDOWS("org.netbeans.api", "org-openide-windows", "RELEASE111"),
    WRAPPER("com.mastfrog", "mastfrog-utils-wrapper", "2.0.5")
    ;
    private final String groupId;
    private final String artifactId;
    private final String version;

    Libraries(String groupId, String artifactId, String version) {
        this.groupId = groupId;
        this.artifactId = artifactId;
        this.version = version;
    }

    @Override
    public String groupId() {
        return groupId;
    }

    @Override
    public String artifactId() {
        return artifactId;
    }

    @Override
    public String version() {
        return version;
    }

    @Override
    public String toString() {
        return groupId + ":" + artifactId + ":" + version;
    }

}
